export default {
  FETCH_MESSAGES_FULFILLED: 'FETCH_MESSAGES_FULFILLED',
  FETCH_MESSAGES_REJECTED: 'FETCH_MESSAGES_REJECTED',
  DELETE_MESSAGE_FULFILLED: 'DELETE_MESSAGE_FULFILLED',
  DELETE_MESSAGE_REJECTED: 'DELETE_MESSAGE_REJECTED',
  POST_MESSAGE_FULFILLED: 'POST_MESSAGE_FULFILLED',
  POST_MESSAGE_REJECTED: 'POST_MESSAGE_REJECTED',
  LOAD_NEXT_PAGE: 'LOAD_NEXT_PAGE',
  LOAD_PREV_PAGE: 'LOAD_PREV_PAGE'
}
